### ISSUE TITLE
simple tutorial / sample code

### ISSUE THREAD

**Issue by DRTEK** [minad/tlsf#1]
Hello 
thank you for your time and effort on this project as well .
can you please add some code snippets showing how to add / remove memory blocks from / back operating system.
thanks again

**Comment by minad** [comment]
You can actually find it here https://github.com/minad/tlsf/blob/master/test.c#L15 and here https://github.com/minad/tlsf/blob/master/test.c#L37
If you execute the testsuite you should see tlsf requesting memory  via tlsf_map and return memory via tlsf_unmap. It is also possible to use mmap and munmap instead of malloc/free in the tlsf_map and tlsf_unmap functions.

Does that help?
